name: Publish Docker
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: kubernetes-images-action
    steps:
      - name: docker login
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} | docker login --username ${{ secrets.DOCKER_PASSWORD }} --password-stdin
      - name: kube-apiserver
        run: |
          docker pull k8s.gcr.io/kube-apiserver:v1.18.6
          docker tag k8s.gcr.io/kube-apiserver:v1.18.6 registry.cn-hangzhou.aliyuncs.com/dunhanson/kube-apiserver:v1.18.6
          docker push registry.cn-hangzhou.aliyuncs.com/dunhanson/kube-apiserver:v1.18.6
          
