name: Publish Docker
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull and push image aliyun
        run: |
          echo "${{ secrets.DOCKER_USERNAME }}" | docker login --username "${{ secrets.DOCKER_PASSWORD }}" --password-stdin
          docker pull k8s.gcr.io/kube-apiserver:v1.18.6
          docker tag k8s.gcr.io/kube-apiserver:v1.18.6 registry.cn-hangzhou.aliyuncs.com/dunhanson/kube-apiserver:v1.18.6
          docker push registry.cn-hangzhou.aliyuncs.com/dunhanson/kube-apiserver:v1.18.6
          
